name: Trigger RPM Release Build

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version Number of release to be created (e.g. 1.2.3)
        type: string
        default: ''
        required: true
jobs:
  trigger-rpm-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Azure CLI script
      uses: azure/cli@v2.0.0
      with:
        azcliversion: latest
        inlineScript: |
          az account show
          apt-get update
          apt-get install jq
          ./run.sh "${{ github.event.inputs.version }}" "${{ secrets.SSH_PUB_KEY }}"
